export const data = [
  {id: 1, name: "Yoga", day: "Monday", instructor: "Jane Doe", date: "03-01-2022", hour: "8", capacity: 1, enrolled: [{id:777, name:"Mordi"}], hall: 1 },
  {id: 2, name: "Yoga", day: "Tuesday", instructor: "Jane Doe", date: "04-01-2022", hour: "12", capacity: 10, enrolled: [], hall: 1 },
  {id: 3, name: "Yoga", day: "Wednesday", instructor: "Jane Doe", date: "05-01-2022", hour: "9", capacity: 10, enrolled: [], hall: 1 },
  {id: 4, name: "Yoga", day: "Thursday", instructor: "Jane Doe", date: "06-01-2022", hour: "10", capacity: 8, enrolled: [], hall: 1 },
  {id: 5, name: "Yoga", day: "Monday", instructor: "Jasmine Smith", date: "03-01-2022", hour: "18", capacity: 8, enrolled: [], hall: 1 },
  {id: 6, name: "Yoga", day: "Tuesday", instructor: "Jasmine Smith", date: "04-01-2022", hour: "20", capacity: 10, enrolled: [], hall: 1 },
  {id: 7, name: "Yoga", day: "Friday", instructor: "Jasmine Smith", date: "07-01-2022", hour: "22", capacity: 10, enrolled: [], hall: 1 },
  {id: 8, name: "Pilates", day: "Tuesday", instructor: "Jasmine Smith", date: "04-01-2022", hour: "13", capacity: 10, enrolled: [], hall: 1 },
  {id: 9, name: "Pilates", day: "Tuesday", instructor: "Jasmine Smith", date: "04-01-2022", hour: "15", capacity: 10, enrolled: [], hall: 1 },
  {id: 10, name: "Pilates", day: "Tuesday", instructor: "Jasmine Smith", date: "04-01-2022", hour: "14", capacity: 8, enrolled: [], hall: 1 },
  {id: 11, name: "Pilates", day: "Thursday", instructor: "Jane Doe", date: "06-01-2022", hour: "18", capacity: 8, enrolled: [], hall: 1 },
  {id: 12, name: "Pilates", day: "Thursday", instructor: "Jane Doe", date: "06-01-2022", hour: "19", capacity: 8, enrolled: [], hall: 1 },
//   { name: "Kickboxing", instructor: "Jonny Smith", date: "", hour: "", capacity: 12, hall: 1 },
//   { name: "Kickboxing", instructor: "Jonny Smith", date: "", hour: "", capacity: 12, hall: 1 },
//   { name: "Kickboxing", instructor: "Jonny Smith", date: "", hour: "", capacity: 12, hall: 1 },
//   { name: "Kickboxing", instructor: "Jonny Smith", date: "", hour: "", capacity: 12, hall: 1 },
//   { name: "Kickboxing", instructor: "Jonny Smith", date: "", hour: "", capacity: 12, hall: 1 },
//   { name: "Kickboxing", instructor: "James Doe", date: "", hour: "", capacity: 10, hall: 1 },
//   { name: "Kickboxing", instructor: "James Doe", date: "", hour: "", capacity: 10, hall: 1 },
//   { name: "Kickboxing", instructor: "James Doe", date: "", hour: "", capacity: 10, hall: 1 },
//   { name: "Aerobics", instructor: "Jonny Smith", date: "", hour: "", capacity: 10, hall: 1 },
//   { name: "Aerobics", instructor: "Jonny Smith", date: "", hour: "", capacity: 10, hall: 1 },
//   { name: "Aerobics", instructor: "Jonny Smith", date: "", hour: "", capacity: 10, hall: 1 },
//   { name: "Aerobics", instructor: "Jonny Smith", date: "", hour: "", capacity: 10, hall: 1 },
//   { name: "Aerobics", instructor: "Jasmine Smith", date: "", hour: "", capacity: 10, hall: 1 },
//   { name: "Aerobics", instructor: "Jasmine Smith", date: "", hour: "", capacity: 10, hall: 1 },
//   { name: "Functional Workout", instructor: "James Doe", date: "", hour: "", capacity: 6, hall: 1 },
//   { name: "Functional Workout", instructor: "James Doe", date: "", hour: "", capacity: 6, hall: 1 },
//   { name: "Functional Workout", instructor: "James Doe", date: "", hour: "", capacity: 6, hall: 1 },
//   { name: "Functional Workout", instructor: "James Doe", date: "", hour: "", capacity: 6, hall: 1 },
//   { name: "Functional Workout", instructor: "James Doe", date: "", hour: "", capacity: 6, hall: 1 }
];
